config/routes.rb
Rails.application.routes.draw do
  resources :postagems
  get "/postagems/:id/remove" => "postagems#destroy"
  root "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/postagem.rb
class Postagem < ApplicationRecord
validates_presence_of :titulo, :conteudo, :photo_file_name
validates_length_of :conteudo, minimum: 10, allow_blank: false

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @postagems = Postagem.take(10)
  end
end

app/controllers/postagem_controller.rb
class PostagemController < ApplicationController
  # chama a view por default no users new (caso não especificado)

  def show
    @postagem = Postagem.find(params[:id])
  end

  def new
    @postagem = Postagem.new
  end

  # def create
  #   @postagem = User.new(user_params)
  #   if @postagem.save
  #     redirect_to @user,
  #                 notice: 'Cadastro criado com sucesso!'
  #   else
  #     render action: :new
  #   end
  # end
  #
  # def edit
  #   @user = User.find(params[:id])
  # end
  #
  # def update
  #   @user = User.find(params[:id])
  #     if @user.update(user_params)
  #       redirect_to @user,
  #       notice: 'Cadastro atualizado com sucesso!'
  #     else
  #       render action: :edit
  #     end
  # end
  #
  # private
  #
  # def user_params
  #   params.
  #   require(:user).
  #   permit(:email, :full_name, :location, :password,
  #             :password_confirmation, :bio)
  # end

end

app/controllers/postagems_controller.rb
class PostagemsController < ApplicationController
  # chama a view por default no users new (caso não especificado)

  def index
    @postagems = Postagem.all
  end

  def show
    @postagem = Postagem.find(params[:id])
  end

  def new
    @postagem = Postagem.new
  end

  def create
    uploaded_io = params[:postagem][:picture]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    other_params = postagem_params
    other_params[:photo_file_name]= check_image_nil uploaded_io.original_filename
    @postagem = Postagem.new(other_params)
    if @postagem.save
      redirect_to root_path
    else
      render action: :new
    end
  end


  def edit
    @postagem = Postagem.find(params[:id])
  end

  def update
    @postagem = Postagem.find(params[:id])
      if @postagem.update(postagem_params)
        redirect_to root_path
      else
        render action: :edit
      end
  end

  def destroy
    id = params[:id]
    Postagem.destroy id
    redirect_to root_path
  end


  def postagem_params
    params.
    require(:postagem).
    permit(:titulo, :subtitulo, :conteudo, :usuario, :data).
    except(:picture)
  end

  def check_image_nil(name)
    if name.empty?
      name = 'post-bg.jpg'
    end
    name
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/postagems_helper.rb
module PostagemsHelper
  def post_date(date)
    # formatting date: 31, Aug 2007 - 9:55PM
    date.strftime("em %m, %b %Y - %H:%M")
  end
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>M4UBlog</title>

    <!-- Bootstrap Core CSS -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="/assets/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/assets/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="./">Home</a>
                    </li>
                    <li>
                        <a href="./postagems/new">Novo Post</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('assets/m4u.png')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <!-- <h1>M4UBlog</h1> -->
                        <!-- <hr class="small"> -->
                        <!-- <span class="subheading">A Clean Blog Theme by Start Bootstrap</span> -->
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                 <% @postagems.reverse_each do |postagem| %>
                  <div class="post-preview">
                      <a href="./postagems/<%= postagem.id %>" >
                          <h2 class="post-title">
                            <%= postagem.titulo %>
                          </h2>
                          <h3 class="post-subtitle">
                            <%= postagem.subtitulo %>
                          </h3>
                      </a>
                      <p class="post-meta">Postado por <%= postagem.usuario %> <%= post_date postagem.created_at %></p>
                  </div>
                  <hr>
                <% end %>


                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">+ Antigos &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                          <span>Follow Us</span>
                            <a href="https://www.facebook.com/M4Umobileforyou/?ref=ts&fref=ts">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://br.linkedin.com/company/m4u">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; M4UBlog 2017</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="/assets/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/assets/bootstrap.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="/assets/jqBootstrapValidation.js"></script>
    <script src="/assets/contact_me.js"></script>

    <!-- Theme JavaScript -->
    <script src="/assets/clean-blog.min.js"></script>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>M4UBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/postagem/edit.html.erb
<h1><%= t '.title' %> </h1>
<%= render 'form' %>
<%= link_to t('links.back'), @user %>

app/views/postagem/new.html.erb
<h1><%= t 'users.new.title' %> </h1>
<%= render 'form' %>
<%= link_to t('links.back'), root_path %>

app/views/postagems/_form.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu <i class="fa fa-bars"></i>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to t('links.Home'), root_path %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('/assets/about-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h2>Escreva sua Notícia</h2>
                    <hr class="small">
                </div>
            </div>
        </div>
    </div>
</header>

 <div class="container">
   <div class="row">
       <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <!-- <p>Escreva sua notícia</p> -->
           <%= form_for @postagem do |f| %>
           <div class="row control-group">
               <div class="form-group col-xs-12 floating-label-form-group controls">
                   <%= f.label :título %>
                   <%= f.text_field :titulo, placeholder: 'Insira o Título'%>
                   <p class="help-block text-danger"></p>
               </div>
           </div>
           <div class="row control-group">
               <div class="form-group col-xs-12 floating-label-form-group controls">
                  <%= f.label :subtítulo %>
                  <%= f.text_field :subtitulo, placeholder: 'Insira o Subtítulo'%>
                   <p class="help-block text-danger"></p>
               </div>
           </div>
           <div class="row control-group">
               <div class="form-group col-xs-12 floating-label-form-group controls">
                   <%= f.label :usuario %>
                   <%= f.text_field :usuario, placeholder: 'Usuário'%>
                   <p class="help-block text-danger"></p>
               </div>
           </div>
           <div class="row control-group">
               <div class="form-group col-xs-12 floating-label-form-group controls">
                 <%= f.label :conteúdo %>
                 <%= f.text_field :conteudo, placeholder: 'Insira o Conteúdo'%>
                   <p class="h#<Am-group col-xs-12 floating-label-form-group controls">
                <%= f.file_field :picture %>
                   <p class="help-block text-danger"></p>
               </div>
           </div>
            <br>
             <div id="success"></div>
             <div class="row">
                 <div class="form-group col-xs-12">
                     <button type="submit" class="btn btn-default">Enviar</button>
                 </div>
             </div>
          <% end %>
       </div>
   </div>
 </div>

app/views/postagems/edit.html.erb
<%= render 'form' %>

app/views/postagems/new.html.erb
<%= render 'form' %>

app/views/postagems/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog - Sample Post</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <%= link_to t('links.Home'), root_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <header class="intro-header" style="background-image: url('/uploads/<%=@postagem.photo_file_name%>')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1><%= @postagem.titulo %></h1>
                        <h2 class="subheading"><%= @postagem.subtitulo %></h2>
                        <span class="meta">Postado por <%= @postagem.usuario %> <%= post_date @postagem.created_at %></span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <p><%= @postagem.conteudo %> </p>
                    <%= link_to 'Editar Postagem', edit_postagem_path(@postagem) %><br>
                    <%= link_to 'Apagar Postagem', "/postagems/#{@postagem.id}/remove" %>
                </div>
            </div>
        </div>
    </article>

    <hr>


    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                          <span>Follow Us</span>
                            <a href="https://www.facebook.com/M4Umobileforyou/?ref=ts&fref=ts">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://br.linkedin.com/company/m4u">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; M4UBlog 2017</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>

    <!-- Theme JavaScript -->
    <script src="js/clean-blog.min.js"></script>

</body>

</html>